#!/usr/bin/env bash
# Bash script displays DNS records:IP address, record typ, subdomains
# subdomain www points to your load-balancer IP

print_record()
{
printf "The subdomain %s is a " "$2"
dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $4 }'
printf " record and points to "
dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $5 }'
echo ""
}
if [ -z "$2" ]; then
    for subdomain in "www" "lb-01" "web-01" "web-02"
    do
	print_record "$1" "$subdomain"
    done
else
    print_record "$1" "$2"
fi

